apiVersion: v1
kind: Service
metadata:
name: mattermost
labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
type: {{ .Values.service.type }}
ports:
- port: 80
    targetPort: 8080
    protocol: TCP
selector:
    app: mattermost