name: ci

on:
  pull_request:
    branches:
      - 'master'
  push:
    tags:
      - 'v*'

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:  
      -
        name: Checkout
        uses: actions/checkout@v2    
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            name/app
            ghcr.io/username/app
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}       
      - 
        name: 'Deploy'
        if: ${{ github.event_name != 'pull_request' }}
        uses: 'deliverybot/helm@v1'
        with:
          release: 'mattermost'
          namespace: 'devops-challenge'
          chart: 'mattermost'
          token: '${{ github.token }}'
          values: |
            service.type: NodePort
            image:
            replicas:3
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'         